let DATA = [ // массив объектов
	{
		id: 1,
		date: '20',
		lecture: 'Лекция 1. Адаптивная вёрстка',
		lecturer: 'Дмитрий Душкин',
		location: 'Москва',
		school: 'Школа Разработки Интерфейсов',
		city: 'Москва',
		company: 'Yandex',
		room: 'Синий Кит',
		startTime: '12:00',
		endTime: '13:30',
	},{
		id: 2,
		date: '27',
		lecture: 'Лекция 2. Работа с сенсорным пользовательским вводом',
		lecturer: 'Дмитрий Душкин',
		location: 'Москва',
		school: 'Школа Разработки Интерфейсов',
		city: 'Москва',
		company: 'Yandex',
		room: 'Синий Кит',
		startTime: '12:00',
		endTime: '13:30',
	},{
		id: 3,
		date: '03',
		lecture: 'Лекция 3. Мультимедиа: возможности браузера',
		lecturer: 'Максим Васильев',
		location: 'Москва',
		school: 'Школа Разработки Интерфейсов',
		city: 'Москва',
		company: 'Yandex',
		room: 'Синий Кит',
		startTime: '12:00',
		endTime: '13:30',
	},{
		id: 4,
		date: '10',
		lecture: 'Лекция 4. Нативные приложения на веб-технологиях',
		lecturer: 'Сергей Бережной',
		location: 'Москва',
		school: 'Школа Разработки Интерфейсов',
		city: 'Москва',
		company: 'Yandex',
		room: 'Синий Кит',
		startTime: '12:00',
		endTime: '13:30',
	},
];

export default DATA
